const BACKEND_URL = import.meta.env.VITE_BACKEND_URL;
const BACKEND_PORT = import.meta.env.VITE_BACKEND_PORT;
const FULL_BACKEND_URL = `${BACKEND_URL}:${BACKEND_PORT}`;

export { FULL_BACKEND_URL, BACKEND_PORT, BACKEND_URL };
