apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
data:
  BACKEND_URL: {{ .Values.backend_config.URL }}
  BACKEND_PORT: {{ .Values.backend_config.PORT }}
