name: Build and deploy

on:
  push:
    branches: cicd
  pull_request:
    branches: main

env:
  IMAGE_NAME: chmonya777/fullggfront
  RELEASE_NAME: fullggfront
  NAMESPACE: fullgg

jobs:
  build:
    runs-on: raspberrypi
    environment: Production
    env:
      VITE_BACKEND_URL: "${{ vars.Production.VITE_BACKEND_URL }}"
      VITE_BACKEND_PORT: "${{ vars.Production.VITE_BACKEND_PORT }}"
    steps:
    - uses: actions/checkout@v4
    - name: Check envs
      run: |
        echo $VITE_BACKEND_URL $VITE_BACKEND_PORT "${{ vars.VITE_BACKEND_URL }}" "${{ vars.VITE_BACKEND_PORT }}" "${{ vars.Production.VITE_BACKEND_URL }}"  "${{ vars.Production.VITE_BACKEND_PORT }}"
    - name: Build image
      run: |
        sudo podman image build --env VITE_BACKEND_URL=$VITE_BACKEND_URL --env VITE_BACKEND_PORT=$VITE_BACKEND_PORT -t $IMAGE_NAME:$GITHUB_SHA .
    - name: Login into dockerhub
      run: |
        sudo podman login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} docker.io
    - name: Push image
      run: |
        sudo podman push $IMAGE_NAME:$GITHUB_SHA
    - name: Delete image locally
      run: |
        sudo podman rmi $IMAGE_NAME:$GITHUB_SHA