name: Build and deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  IMAGE_NAME: chmonya777/fullggfront
  RELEASE_NAME: fullggfront
  NAMESPACE: fullgg

jobs:
  build:
    runs-on: raspberrypi
    env:
      VITE_BACKEND_URL: "${{ vars.VITE_BACKEND_URL }}"
      VITE_BACKEND_PORT: "${{ vars.VITE_BACKEND_PORT }}"
    steps:
    - uses: actions/checkout@v4
    - name: Check envs
      run: |
        echo $VITE_BACKEND_URL $VITE_BACKEND_PORT "${{ vars.VITE_BACKEND_URL }}" "${{ vars.VITE_BACKEND_PORT }}"
    - name: Build image
      run: |
        sudo podman image build --env VITE_BACKEND_URL=$VITE_BACKEND_URL --env VITE_BACKEND_PORT=$VITE_BACKEND_PORT -t $IMAGE_NAME:$GITHUB_SHA .
    - name: Login into dockerhub
      run: |
        sudo podman login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} docker.io
    - name: Push image
      run: |
        sudo podman push $IMAGE_NAME:$GITHUB_SHA
    - name: Delete image locally
      run: |
        sudo podman rmi $IMAGE_NAME:$GITHUB_SHA
  deploy:
    needs: build
    runs-on: raspberrypi
    steps:
    - name: Apply deployment
      run: |
        helm secrets upgrade $RELEASE_NAME .helm \
          --install \
          --set-string image.name=$IMAGE_NAME \
          --set-string image.tag=$GITHUB_SHA \
          --namespace=$NAMESPACE \
          -f .helm/values.yaml
    - name: Wait for deploy
      run: kubectl rollout status deployment $RELEASE_NAME --namespace=$NAMESPACE --timeout=300s
